supporting port and db port flags

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,4 +1,7 @@
 #!/bin/bash
+
+PG_PORT=5332
+
 # trap ctrl-c and call ctrl_c()
 trap ctrl_c INT
 
@@ -11,46 +14,72 @@ function ctrl_c() {
     cd ..
 }
 
-# First of all, ensuring dependencies are installed and checking node_modules
-if [ ! -d "node_modules" ]; then
-    echo "Installing dependencies"
+# Function to check if we are on the first run with the .RUN file
+function is_first_run() {
+    if [ ! -f ".RUN" ]; then
+        return 0
+    else
+        return 1
+    fi
+}
+
+
+# If we are on the first run, we need to install the dependencies
+if is_first_run; then
+    echo "Installing node dependencies"
     if ! yarn install; then
         echo "Error: Dependencies failed to install"
         exit 1
     fi
-fi
-
-# We need docker and docker compose to be installed
-if ! docker compose version; then
-    echo "Error: Docker and docker compose are not installed: please refer to https://docs.docker.com/compose/install/"
-    exit 1
+    echo "Ok, dependencies installed"
+    # We need docker and docker compose to be installed
+    if ! docker compose version; then
+        echo "Error: Docker and docker compose are not installed: please refer to https://docs.docker.com/compose/install/"
+        exit 1
+    fi
+    echo "Ok, docker compose installed"
+    # This file is used to check if we are on the first run
+    touch .RUN
 fi
 
 CLEAN=false
-# Supporting cleanup of the database
-if [ "$1" == "--clean" ]; then
-    CLEAN=true
-elif [ "$1" == "--help" ]; then
-    echo "Usage: $0 [--clean]"
-    exit 0
-fi
+PORT=53550
 
-# Database management
-cd postgres
+while getopts "p:d:" opt; do
+    case $opt in
+        p) PORT=$OPTARG;;
+        d) PG_PORT=$OPTARG;;
+        #...
+    esac
+done
+shift $((OPTIND -1))
+echo "PORT=$PORT"
+echo "PG_PORT=$PG_PORT"
+
+# PG_PORT is exported for both docker and yarn
+export PG_PORT=$PG_PORT
+
+# Database management with proper folder based on the port
+PG_FOLDER="postgres_${PG_PORT}"
+if [ ! -d "$PG_FOLDER" ]; then
+    cp -r postgres $PG_FOLDER   
+fi
+cd $PG_FOLDER
+
 # Suppressing errors if the database is not running
 docker compose down > /dev/null 2>&1
 if [ "$CLEAN" == "true" ]; then
-    sudo rm -rf data
-    mkdir data
+    sudo rm -rf data_${PG_PORT}
+    mkdir data_${PG_PORT}
 fi  
 # Finally starting the database
 docker compose up -d
 cd ..
 
-# Waiting for port 5332 to be available
+# Waiting for db port to be available
 echo -n "Waiting for the database to be available"
 COUNT=0
-while ! nc -z localhost 5332; do
+while ! nc -z localhost $PG_PORT; do
     echo -n "."
     COUNT=$((COUNT+1))
     if [ $COUNT -gt 10 ]; then
@@ -61,7 +90,7 @@ while ! nc -z localhost 5332; do
 done
 
 # Starting the node managing errors
-if ! yarn start; then
+if ! RPC_PORT=$PORT PG_PORT=$PG_PORT yarn start; then
     if [ "$HAS_BEEN_INTERRUPTED" == "true" ]; then
         echo "RPC exited successfully"
     else
@@ -74,6 +103,6 @@ else
 fi
 
 # Once exiting, stopping the database
-cd postgres
+cd postgres_${PG_PORT}
 docker compose down
 cd ..
